using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core
{
    public class CountryList
    {
        public List<Country> country { get; set; }
        public CountryList()
        {
            country = new List<Country>();
            country.Add(new Country() { code = "", name = "Select Country" });
            country.Add(new Country() { code = "IN", name = "India" });
            country.Add(new Country() { code = "", name = "----------" });
            country.Add(new Country() { code = "AF", name = "Afghanistan", });
            country.Add(new Country() { code = "AX", name = "Aland Islands" });
            country.Add(new Country() { code = "AL", name = "Albania" });
            country.Add(new Country() { code = "DZ", name = "Algeria" });
            country.Add(new Country() { code = "AS", name = "American Samoa" });
            country.Add(new Country() { code = "AD", name = "Andorra" });
            country.Add(new Country() { code = "AO", name = "Angola" });
            country.Add(new Country() { code = "AI", name = "Anguilla" });
            country.Add(new Country() { code = "AQ", name = "Antarctica" });
            country.Add(new Country() { code = "AG", name = "Antigua and Barbuda" });
            country.Add(new Country() { code = "AR", name = "Argentina" });
            country.Add(new Country() { code = "AM", name = "Armenia" });
            country.Add(new Country() { code = "AW", name = "Aruba" });
            country.Add(new Country() { code = "AU", name = "Australia" });
            country.Add(new Country() { code = "AT", name = "Austria" });
            country.Add(new Country() { code = "AZ", name = "Azerbaijan" });
            country.Add(new Country() { code = "BS", name = "Bahamas" });
            country.Add(new Country() { code = "BH", name = "Bahrain" });
            country.Add(new Country() { code = "BD", name = "Bangladesh" });
            country.Add(new Country() { code = "BB", name = "Barbados" });
            country.Add(new Country() { code = "BY", name = "Belarus" });
            country.Add(new Country() { code = "BE", name = "Belgium" });
            country.Add(new Country() { code = "BZ", name = "Belize" });
            country.Add(new Country() { code = "BJ", name = "Benin" });
            country.Add(new Country() { code = "BM", name = "Bermuda" });
            country.Add(new Country() { code = "BT", name = "Bhutan" });
            country.Add(new Country() { code = "BO", name = "Bolivia" });
            country.Add(new Country() { code = "BA", name = "Bosnia and Herzegovina" });
            country.Add(new Country() { code = "BW", name = "Botswana" });
            country.Add(new Country() { code = "BV", name = "Bouvet Island" });
            country.Add(new Country() { code = "BR", name = "Brazil" });
            country.Add(new Country() { code = "IO", name = "British Indian Ocean Territory" });
            country.Add(new Country() { code = "BN", name = "Brunei Darussalam" });
            country.Add(new Country() { code = "BG", name = "Bulgaria" });
            country.Add(new Country() { code = "BF", name = "Burkina Faso" });
            country.Add(new Country() { code = "BI", name = "Burundi" });
            country.Add(new Country() { code = "KH", name = "Cambodia" });
            country.Add(new Country() { code = "CM", name = "Cameroon" });
            country.Add(new Country() { code = "CA", name = "Canada" });
            country.Add(new Country() { code = "CV", name = "Cape Verde" });
            country.Add(new Country() { code = "KY", name = "Cayman Islands" });
            country.Add(new Country() { code = "CF", name = "Central African Republic" });
            country.Add(new Country() { code = "TD", name = "Chad" });
            country.Add(new Country() { code = "CL", name = "Chile" });
            country.Add(new Country() { code = "CN", name = "China" });
            country.Add(new Country() { code = "CX", name = "Christmas Island" });
            country.Add(new Country() { code = "CC", name = "Cocos (Keeling) Islands" });
            country.Add(new Country() { code = "CO", name = "Colombia" });
            country.Add(new Country() { code = "KM", name = "Comoros" });
            country.Add(new Country() { code = "CG", name = "Congo" });
            country.Add(new Country() { code = "CD", name = "Congo The Democratic Republic of the" });
            country.Add(new Country() { code = "CK", name = "Cook Islands" });
            country.Add(new Country() { code = "CR", name = "Costa Rica" });
            country.Add(new Country() { code = "CI", name = "C&#244;te d'Ivoire" });
            country.Add(new Country() { code = "HR", name = "Croatia" });
            country.Add(new Country() { code = "CU", name = "Cuba" });
            country.Add(new Country() { code = "CY", name = "Cyprus" });
            country.Add(new Country() { code = "CZ", name = "Czech Republic" });
            country.Add(new Country() { code = "DK", name = "Denmark" });
            country.Add(new Country() { code = "DJ", name = "Djibouti" });
            country.Add(new Country() { code = "DM", name = "Dominica" });
            country.Add(new Country() { code = "DO", name = "Dominican Republic" });
            country.Add(new Country() { code = "EC", name = "Ecuador" });
            country.Add(new Country() { code = "EG", name = "Egypt" });
            country.Add(new Country() { code = "SV", name = "El Salvador" });
            country.Add(new Country() { code = "GQ", name = "Equatorial Guinea" });
            country.Add(new Country() { code = "ER", name = "Eritrea" });
            country.Add(new Country() { code = "EE", name = "Estonia" });
            country.Add(new Country() { code = "ET", name = "Ethiopia" });
            country.Add(new Country() { code = "FK", name = "Falkland Islands (Malvinas)" });
            country.Add(new Country() { code = "FO", name = "Faroe Islands" });
            country.Add(new Country() { code = "FJ", name = "Fiji" });
            country.Add(new Country() { code = "FI", name = "Finland" });
            country.Add(new Country() { code = "FR", name = "France" });
            country.Add(new Country() { code = "GF", name = "French Guiana" });
            country.Add(new Country() { code = "PF", name = "French Polynesia" });
            country.Add(new Country() { code = "TF", name = "French Southern Territories" });
            country.Add(new Country() { code = "GA", name = "Gabon" });
            country.Add(new Country() { code = "GM", name = "Gambia" });
            country.Add(new Country() { code = "GE", name = "Georgia" });
            country.Add(new Country() { code = "DE", name = "Germany" });
            country.Add(new Country() { code = "GH", name = "Ghana" });
            country.Add(new Country() { code = "GI", name = "Gibraltar" });
            country.Add(new Country() { code = "GR", name = "Greece" });
            country.Add(new Country() { code = "GL", name = "Greenland" });
            country.Add(new Country() { code = "GD", name = "Grenada" });
            country.Add(new Country() { code = "GP", name = "Guadeloupe" });
            country.Add(new Country() { code = "GU", name = "Guam" });
            country.Add(new Country() { code = "GT", name = "Guatemala" });
            country.Add(new Country() { code = "GG", name = "Guernsey" });
            country.Add(new Country() { code = "GN", name = "Guinea" });
            country.Add(new Country() { code = "GW", name = "Guinea-Bissau" });
            country.Add(new Country() { code = "GY", name = "Guyana" });
            country.Add(new Country() { code = "HT", name = "Haiti" });
            country.Add(new Country() { code = "HM", name = "Heard Island and McDonald Islands" });
            country.Add(new Country() { code = "VA", name = "Holy See (Vatican City State)" });
            country.Add(new Country() { code = "HN", name = "Honduras" });
            country.Add(new Country() { code = "HK", name = "Hong Kong" });
            country.Add(new Country() { code = "HU", name = "Hungary" });
            country.Add(new Country() { code = "IS", name = "Iceland" });
            country.Add(new Country() { code = "ID", name = "Indonesia" });
            country.Add(new Country() { code = "IR", name = "Iran Islamic Republic of" });
            country.Add(new Country() { code = "IQ", name = "Iraq" });
            country.Add(new Country() { code = "IE", name = "Ireland" });
            country.Add(new Country() { code = "IM", name = "Isle of Man" });
            country.Add(new Country() { code = "IL", name = "Israel" });
            country.Add(new Country() { code = "IT", name = "Italy" });
            country.Add(new Country() { code = "JM", name = "Jamaica" });
            country.Add(new Country() { code = "JP", name = "Japan" });
            country.Add(new Country() { code = "JE", name = "Jersey" });
            country.Add(new Country() { code = "JO", name = "Jordan" });
            country.Add(new Country() { code = "KZ", name = "Kazakhstan" });
            country.Add(new Country() { code = "KE", name = "Kenya" });
            country.Add(new Country() { code = "KI", name = "Kiribati" });
            country.Add(new Country() { code = "KP", name = "Korea Democratic People's Republic of" });
            country.Add(new Country() { code = "KR", name = "Korea Republic of" });
            country.Add(new Country() { code = "KW", name = "Kuwait" });
            country.Add(new Country() { code = "KG", name = "Kyrgyzstan" });
            country.Add(new Country() { code = "LA", name = "Lao People's Democratic Republic" });
            country.Add(new Country() { code = "LV", name = "Latvia" });
            country.Add(new Country() { code = "LB", name = "Lebanon" });
            country.Add(new Country() { code = "LS", name = "Lesotho" });
            country.Add(new Country() { code = "LR", name = "Liberia" });
            country.Add(new Country() { code = "LY", name = "Libyan Arab Jamahiriya" });
            country.Add(new Country() { code = "LI", name = "Liechtenstein" });
            country.Add(new Country() { code = "LT", name = "Lithuania" });
            country.Add(new Country() { code = "LU", name = "Luxembourg" });
            country.Add(new Country() { code = "MO", name = "Macao" });
            country.Add(new Country() { code = "MK", name = "Macedonia The Former Yugoslav Republic of" });
            country.Add(new Country() { code = "MG", name = "Madagascar" });
            country.Add(new Country() { code = "MW", name = "Malawi" });
            country.Add(new Country() { code = "MY", name = "Malaysia" });
            country.Add(new Country() { code = "MV", name = "Maldives" });
            country.Add(new Country() { code = "ML", name = "Mali" });
            country.Add(new Country() { code = "MT", name = "Malta" });
            country.Add(new Country() { code = "MH", name = "Marshall Islands" });
            country.Add(new Country() { code = "MQ", name = "Martinique" });
            country.Add(new Country() { code = "MR", name = "Mauritania" });
            country.Add(new Country() { code = "MU", name = "Mauritius" });
            country.Add(new Country() { code = "YT", name = "Mayotte" });
            country.Add(new Country() { code = "MX", name = "Mexico" });
            country.Add(new Country() { code = "FM", name = "Microneia Federated States of" });
            country.Add(new Country() { code = "MD", name = "Moldova" });
            country.Add(new Country() { code = "MC", name = "Monaco" });
            country.Add(new Country() { code = "MN", name = "Mongolia" });
            country.Add(new Country() { code = "ME", name = "Montenegro" });
            country.Add(new Country() { code = "MS", name = "Montserrat" });
            country.Add(new Country() { code = "MA", name = "Morocco" });
            country.Add(new Country() { code = "MZ", name = "Mozambique" });
            country.Add(new Country() { code = "MM", name = "Myanmar" });
            country.Add(new Country() { code = "NA", name = "Namibia" });
            country.Add(new Country() { code = "NR", name = "Nauru" });
            country.Add(new Country() { code = "NP", name = "Nepal" });
            country.Add(new Country() { code = "NL", name = "Netherlands" });
            country.Add(new Country() { code = "AN", name = "Netherlands Antilles" });
            country.Add(new Country() { code = "NC", name = "New Caledonia" });
            country.Add(new Country() { code = "NZ", name = "New Zealand" });
            country.Add(new Country() { code = "NI", name = "Nicaragua" });
            country.Add(new Country() { code = "NE", name = "Niger" });
            country.Add(new Country() { code = "NG", name = "Nigeria" });
            country.Add(new Country() { code = "NU", name = "Niue" });
            country.Add(new Country() { code = "NF", name = "Norfolk Island" });
            country.Add(new Country() { code = "MP", name = "Northern Mariana Islands" });
            country.Add(new Country() { code = "NO", name = "Norway" });
            country.Add(new Country() { code = "OM", name = "Oman" });
            country.Add(new Country() { code = "PK", name = "Pakistan" });
            country.Add(new Country() { code = "PW", name = "Palau" });
            country.Add(new Country() { code = "PS", name = "Palestinian Territory Occupied" });
            country.Add(new Country() { code = "PA", name = "Panama" });
            country.Add(new Country() { code = "PG", name = "Papua New Guinea" });
            country.Add(new Country() { code = "PY", name = "Paraguay" });
            country.Add(new Country() { code = "PE", name = "Peru" });
            country.Add(new Country() { code = "PH", name = "Philippines" });
            country.Add(new Country() { code = "PN", name = "Pitcairn" });
            country.Add(new Country() { code = "PL", name = "Poland" });
            country.Add(new Country() { code = "PT", name = "Portugal" });
            country.Add(new Country() { code = "PR", name = "Puerto Rico" });
            country.Add(new Country() { code = "QA", name = "Qatar" });
            country.Add(new Country() { code = "RE", name = "R&#233;union" });
            country.Add(new Country() { code = "RO", name = "Romania" });
            country.Add(new Country() { code = "RU", name = "Russian Federation" });
            country.Add(new Country() { code = "RW", name = "Rwanda" });
            country.Add(new Country() { code = "BL", name = "Saint Barth&#233;lemy" });
            country.Add(new Country() { code = "SH", name = "Saint Helena" });
            country.Add(new Country() { code = "KN", name = "Saint Kitts and Nevis" });
            country.Add(new Country() { code = "LC", name = "Saint Lucia" });
            country.Add(new Country() { code = "MF", name = "Saint Martin" });
            country.Add(new Country() { code = "PM", name = "Saint Pierre and Miquelon" });
            country.Add(new Country() { code = "VC", name = "Saint Vincent and the Grenadines" });
            country.Add(new Country() { code = "WS", name = "Samoa" });
            country.Add(new Country() { code = "SM", name = "San Marino" });
            country.Add(new Country() { code = "ST", name = "Sao Tome and Principe" });
            country.Add(new Country() { code = "SA", name = "Saudi Arabia" });
            country.Add(new Country() { code = "SN", name = "Senegal" });
            country.Add(new Country() { code = "RS", name = "Serbia" });
            country.Add(new Country() { code = "SC", name = "Seychelles" });
            country.Add(new Country() { code = "SL", name = "Sierra Leone" });
            country.Add(new Country() { code = "SG", name = "Singapore" });
            country.Add(new Country() { code = "SK", name = "Slovakia" });
            country.Add(new Country() { code = "SI", name = "Slovenia" });
            country.Add(new Country() { code = "SB", name = "Solomon Islands" });
            country.Add(new Country() { code = "SO", name = "Somalia" });
            country.Add(new Country() { code = "ZA", name = "South Africa" });
            country.Add(new Country() { code = "GS", name = "South Georgia and the South Sandwich Islands" });
            country.Add(new Country() { code = "ES", name = "Spain" });
            country.Add(new Country() { code = "LK", name = "Sri Lanka" });
            country.Add(new Country() { code = "SD", name = "Sudan" });
            country.Add(new Country() { code = "SR", name = "Suriname" });
            country.Add(new Country() { code = "SJ", name = "Svalbard and Jan Mayen" });
            country.Add(new Country() { code = "SZ", name = "Swaziland" });
            country.Add(new Country() { code = "SE", name = "Sweden" });
            country.Add(new Country() { code = "CH", name = "Switzerland" });
            country.Add(new Country() { code = "SY", name = "Syrian Arab Republic" });
            country.Add(new Country() { code = "TW", name = "Taiwan Province of China" });
            country.Add(new Country() { code = "TJ", name = "Tajikistan" });
            country.Add(new Country() { code = "TZ", name = "Tanzania United Republic of" });
            country.Add(new Country() { code = "TH", name = "Thailand" });
            country.Add(new Country() { code = "TL", name = "Timor-Leste" });
            country.Add(new Country() { code = "TG", name = "Togo" });
            country.Add(new Country() { code = "TK", name = "Tokelau" });
            country.Add(new Country() { code = "TO", name = "Tonga" });
            country.Add(new Country() { code = "TT", name = "Trinidad and Tobago" });
            country.Add(new Country() { code = "TN", name = "Tunisia" });
            country.Add(new Country() { code = "TR", name = "Turkey" });
            country.Add(new Country() { code = "TM", name = "Turkmenistan" });
            country.Add(new Country() { code = "TC", name = "Turks and Caicos Islands" });
            country.Add(new Country() { code = "TV", name = "Tuvalu" });
            country.Add(new Country() { code = "UG", name = "Uganda" });
            country.Add(new Country() { code = "UA", name = "Ukraine" });
            country.Add(new Country() { code = "AE", name = "United Arab Emirates" });
            country.Add(new Country() { code = "UM", name = "United States Minor Outlying Islands" });
            country.Add(new Country() { code = "US", name = "United States" });
            country.Add(new Country() { code = "UY", name = "Uruguay" });
            country.Add(new Country() { code = "UZ", name = "Uzbekistan" });
            country.Add(new Country() { code = "VU", name = "Vanuatu" });
            country.Add(new Country() { code = "VE", name = "Venezuela" });
            country.Add(new Country() { code = "VN", name = "Viet Nam" });
            country.Add(new Country() { code = "VG", name = "Virgin Islands British" });
            country.Add(new Country() { code = "VI", name = "Virgin Islands U.S." });
            country.Add(new Country() { code = "WF", name = "Wallis and Futuna" });
            country.Add(new Country() { code = "EH", name = "Western Sahara" });
            country.Add(new Country() { code = "YE", name = "Yemen" });
            country.Add(new Country() { code = "ZM", name = "Zambia" });
            country.Add(new Country() { code = "ZW", name = "Zimbabwe" });
        }
    }
    public class Country
    {
        public string code { get; set; }
        public string name { get; set; }
    }
}
